name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore pattng.jks \
            -alias pattng \
            -keyalg RSA \
            -keysize 4096 \
            -validity 10000 \
            -storepass "PattSNG@2026" \
            -keypass "PattSNG@2026" \
            -dname "CN=PattSNG, OU=Android, O=Development, L=Chicago, ST=IL, C=US"

          base64 -w 0 pattng.jks > pattng.jks.b64

      - name: Upload Keystore Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            pattng.jks
            pattng.jks.b64
